"""Pydantic models for structured agent communication."""

from enum import Enum
from typing import Literal, Optional, Any, Dict, List
from pydantic import BaseModel, Field
from datetime import datetime


class TaskType(str, Enum):
    CODING = "coding"
    TESTING = "testing"
    REVIEW = "review"


class TaskStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    WAITING_FOR_INPUT = "waiting_for_input"


class ModelTier(str, Enum):
    """Model tiers based on capability and cost."""

    PREMIUM = "premium"  # Kimi K2, Claude Sonnet
    ADVANCED = "advanced"  # GLM-4.6, GPT-4o
    STANDARD = "standard"  # GPT-4o-mini, gemini-1.5-flash
    LOCAL = "local"  # Fine-tuned local models


class AgentConfig(BaseModel):
    """Configuration for a sub-agent."""

    agent_type: TaskType
    model_tier: ModelTier
    max_tokens: int = 4000
    temperature: float = 0.2
    timeout_seconds: int = 300


class ExecutionResult(BaseModel):
    """Result of code execution or command."""

    exit_code: int
    stdout: str
    stderr: str
    duration_seconds: float
    command: str


class ConsoleSummary(BaseModel):
    """Summarized console output - always generated by cheap model."""

    summary: str = Field(description="Brief summary of what happened")
    key_errors: List[str] = Field(
        default_factory=list, description="Critical errors found"
    )
    warnings: List[str] = Field(default_factory=list, description="Warnings to note")
    success_indicators: List[str] = Field(
        default_factory=list, description="Successful operations"
    )
    metrics: Dict[str, Any] = Field(
        default_factory=dict, description="Key metrics extracted"
    )
    relevant_files: List[str] = Field(
        default_factory=list, description="Files mentioned in output"
    )
    action_needed: bool = Field(
        default=False, description="Whether human intervention needed"
    )


class SubTask(BaseModel):
    """Task assigned to a sub-agent."""

    task_type: TaskType = Field(
        description="the specialized agent the task should be routed to"
    )
    description: str = Field(description="A full description of the task")
    context: Dict[str, Any] = Field(
        default_factory=dict,
        description="any relevant information helpful for completing the task",
    )
    agent_config: AgentConfig


class Plan(BaseModel):
    subtasks: List[SubTask]


class SubAgentResult(BaseModel):
    """Result returned by sub-agent."""

    task_id: str
    status: TaskStatus
    result: Optional[str] = None
    execution_result: Optional[ExecutionResult] = None
    console_summary: Optional[ConsoleSummary] = None
    token_usage: Dict[str, int] = Field(default_factory=dict)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    completed_at: datetime = Field(default_factory=datetime.now)

    class Config:
        use_enum_values = True


class ProjectHints(BaseModel):
    """Project-specific hints from .dude.yaml."""

    language: str = "python"
    framework: Optional[str] = None
    test_framework: Optional[str] = None
    test_command: str = "pytest"
    lint_command: Optional[str] = None
    build_command: Optional[str] = None
    code_style: str = "pep8"
    project_type: str = "library"
    exclude_patterns: List[str] = Field(default_factory=list)
    additional_context: Dict[str, Any] = Field(default_factory=dict)
