"""Pydantic models for structured agent communication."""

from enum import Enum
from typing import Literal, Optional, Any, Dict, List
from pydantic import BaseModel, Field
from datetime import datetime


class TaskType(str, Enum):
    PLANNING = "planning"
    CODING = "coding"
    TESTING = "testing"
    REVIEW = "review"
    DEBUGGING = "debugging"
    SUMMARIZATION = "summarization"


class TaskStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    WAITING_FOR_INPUT = "waiting_for_input"


class ModelTier(str, Enum):
    """Model tiers based on capability and cost."""
    PREMIUM = "premium"  # Kimi K2, Claude Sonnet
    ADVANCED = "advanced"  # GLM-4.6, GPT-4o
    STANDARD = "standard"  # GPT-4o-mini, gemini-1.5-flash
    LOCAL = "local"  # Fine-tuned local models


class AgentConfig(BaseModel):
    """Configuration for a sub-agent."""
    agent_type: TaskType
    model_tier: ModelTier
    max_tokens: int = 4000
    temperature: float = 0.2
    timeout_seconds: int = 300


class ExecutionResult(BaseModel):
    """Result of code execution or command."""
    exit_code: int
    stdout: str
    stderr: str
    duration_seconds: float
    command: str


class ConsoleSummary(BaseModel):
    """Summarized console output - always generated by cheap model."""
    summary: str = Field(description="Brief summary of what happened")
    key_errors: List[str] = Field(default_factory=list, description="Critical errors found")
    warnings: List[str] = Field(default_factory=list, description="Warnings to note")
    success_indicators: List[str] = Field(default_factory=list, description="Successful operations")
    metrics: Dict[str, Any] = Field(default_factory=dict, description="Key metrics extracted")
    relevant_files: List[str] = Field(default_factory=list, description="Files mentioned in output")
    action_needed: bool = Field(default=False, description="Whether human intervention needed")


class SubTask(BaseModel):
    """Task assigned to a sub-agent."""
    task_id: str
    parent_id: Optional[str] = None
    task_type: TaskType
    description: str
    context: Dict[str, Any] = Field(default_factory=dict)
    agent_config: AgentConfig
    created_at: datetime = Field(default_factory=datetime.now)
    max_iterations: int = 10
    
    class Config:
        use_enum_values = True


class SubAgentResult(BaseModel):
    """Result returned by sub-agent."""
    task_id: str
    status: TaskStatus
    result: Optional[str] = None
    execution_result: Optional[ExecutionResult] = None
    console_summary: Optional[ConsoleSummary] = None
    token_usage: Dict[str, int] = Field(default_factory=dict)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    completed_at: datetime = Field(default_factory=datetime.now)
    
    class Config:
        use_enum_values = True


class TaskDefinition(BaseModel):
    """High-level task definition from user or GitHub."""
    task_id: str
    source: Literal["cli", "github_issue", "github_pr"]
    title: str
    description: str
    context: Dict[str, Any] = Field(default_factory=dict)
    project_hints: Optional[Dict[str, Any]] = None
    created_at: datetime = Field(default_factory=datetime.now)
    github_data: Optional[Dict[str, Any]] = None  # issue/pr metadata
    
    def to_sub_task(self, task_type: TaskType, agent_config: AgentConfig) -> SubTask:
        """Convert to sub-task for agent execution."""
        return SubTask(
            task_id=f"{self.task_id}-{task_type.value}",
            parent_id=self.task_id,
            task_type=task_type,
            description=self.description,
            context={**self.context, "github_data": self.github_data},
            agent_config=agent_config,
        )


class SessionState(BaseModel):
    """Complete state of a session."""
    session_id: str
    task_definition: TaskDefinition
    sub_tasks: List[SubTask] = Field(default_factory=list)
    completed_tasks: List[SubAgentResult] = Field(default_factory=list)
    todo_list: List[str] = Field(default_factory=list)
    status: TaskStatus = TaskStatus.PENDING
    token_usage_total: Dict[str, int] = Field(default_factory=dict)
    cost_total: float = 0.0
    start_time: datetime = Field(default_factory=datetime.now)
    end_time: Optional[datetime] = None
    current_branch: Optional[str] = None
    git_commit: Optional[str] = None
    
    class Config:
        use_enum_values = True


class ProjectHints(BaseModel):
    """Project-specific hints from .dude.yaml."""
    language: str = "python"
    framework: Optional[str] = None
    test_framework: Optional[str] = None
    test_command: str = "pytest"
    lint_command: Optional[str] = None
    build_command: Optional[str] = None
    code_style: str = "pep8"
    project_type: str = "library"
    exclude_patterns: List[str] = Field(default_factory=list)
    additional_context: Dict[str, Any] = Field(default_factory=dict)


class GitHubWebhookPayload(BaseModel):
    """Simplified GitHub webhook payload."""
    event: str
    action: str
    repository: Dict[str, Any]
    sender: Dict[str, Any]
    installation: Optional[Dict[str, Any]] = None
    # Issue/PR specific fields
    issue: Optional[Dict[str, Any]] = None
    pull_request: Optional[Dict[str, Any]] = None
    comment: Optional[Dict[str, Any]] = None
    
    @property
    def is_issue(self) -> bool:
        return self.issue is not None
    
    @property
    def is_pull_request(self) -> bool:
        return self.pull_request is not None
    
    @property
    def is_comment(self) -> bool:
        return self.comment is not None
